PriceTag/Models/TagViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PriceTag.Models
{
    public class CreateTagVM
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public DateTime CreateAt { get; set; }
        public DateTime UpdateAt { get; set; }
    }
}

PriceTag/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using PriceTag.Service;
using Repository.Pattern.UnitOfWork;
using PriceTag.Models;
using PriceTag.Entities.Models;
using Repository.Pattern.Infrastructure;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Web.Helpers;

namespace PriceTag.Controllers
{
    public class TagController : BaseController
    {
        private readonly ITagService _tagService;
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;

        public TagController()
        {
            _unitOfWorkAsync = DependencyResolver.Current.GetService<IUnitOfWorkAsync>();
            _tagService = DependencyResolver.Current.GetService<ITagService>();
        }

        // GET: Tag
        public ActionResult Index()
        {
            
            return View();
        }

        // GET: Tag/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Tag/Create
        public ActionResult Create()
        {
            ViewBag.UserName = User.Identity.GetUserName();

            return View();
        }

        // POST: Tag/Create
        [HttpPost]
        public ActionResult Create(CreateTagVM model)
        {
            if (ModelState.IsValid)
            {
                Tag tag = new Tag
                {
                    Title = model.Title,
                    UserId = User.Identity.GetUserId(),
                    Price = 0,
                    CreateAt = DateTime.Now,
                    UpdateAt = DateTime.Now
                };


                tag.ObjectState = ObjectState.Added;
                _tagService.Insert(tag);

                try
                {
                    _unitOfWorkAsync.SaveChanges();
                }
                catch (DbUpdateException)
                {
                    throw;
                }

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Upload(int id)
        {
            var image = WebImage.GetImageFromRequest();
            //var physicalPath = Path.Combine(Server.MapPath("~/App_Data"), image.FileName);

            //// Delete File - not working
            //var fi = new FileInfo(physicalPath);
            //fi.Delete();

            return Json("");
        }

        // GET: Tag/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Tag/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Tag/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Tag/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PriceTag/Controllers/api/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Web;
using System.IO;

namespace PriceTag.Controllers.api
{
    public class TagController : ApiController
    {
        //Multiple Uploads
        [HttpPost]
        public async Task<HttpResponseMessage> Uploads()
        {
            // Check if the request contains multipart/form-data.
            if (!Request.Content.IsMimeMultipartContent())
            {
                throw new HttpResponseException(HttpStatusCode.UnsupportedMediaType);
            }

            var provider = GetMultipartProvider();

            // Read the form data.
            var result = await Request.Content.ReadAsMultipartAsync(provider);

            int id = 0;

            Int32.TryParse(provider.FormData.GetValues("id")[0], out id);

            // Delete File - not working
            //var fi = new FileInfo(result.FileData.First().LocalFileName);
            //fi.Delete();

            return Request.CreateResponse(HttpStatusCode.OK);

        }

        // You could extract these two private methods to a separate utility class since
        // they do not really belong to a controller class but that is up to you
        private MultipartFormDataStreamProvider GetMultipartProvider()
        {
            // IMPORTANT: replace "(tilde)" with the real tilde character
            // (our editor doesn't allow it, so I just wrote "(tilde)" instead)
            var uploadFolder = "~/App_Data"; // you could put this to web.config
            var root = HttpContext.Current.Server.MapPath(uploadFolder);
            Directory.CreateDirectory(root);
            return new MultipartFormDataStreamProvider(root);
        }
    }
}

PriceTag/Views/Tag/Create.cshtml
@model PriceTag.Models.CreateTagVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@ViewBag.UserName
@using (Html.BeginForm("Create", "Tag", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>

}

PriceTag/Views/Tag/Upload.cshtml
<div class="gallery" data-ng-controller="ListingImageCtrl">
    <!-- Loading -->
    <div cg-busy="myPromise"></div>

    <!-- Alert -->
    <div class="alert alert-{{alert.type}} alert-dismissable" data-ng-show="alert.display">
        <a class="close" data-ng-click="alert.display=false" href="#">&times;</a>
        <div data-ng-bind-html="alert.message"></div>
    </div>

    <form name="formUpload" method="post" enctype="multipart/form-data" action="/tag/upload" ng-upload>
        <!-- No File -->
        <div class="no-gallery" data-ng-show="!draftFiles.length && !files.length">
            <div class="center">
                <img src="http://detail.herokuapp.com/img/no-img-gallery.png" alt="no-gallery">
                <p class="no-gallery-label">You don't have any images</p>
                <p>Click 'Add Image' to attach photos or drag & drop your photos here.</p>
                <div class="btn-glow primary fileinput-button">
                    <i class="fa fa-plus"></i>
                    <input id="file-input" name="image" type="file" multiple accept="image/*" />
                    <span>Add new image</span>
                </div>
            </div>
        </div>
        <div class="gallery-wrapper" data-ng-show="files.length || draftFiles.length">
            <div class="row gallery-row">
                <!-- Image -->
                <div class="col-xs-6 col-md-3 img-container" data-ng-repeat="file in files">
                    <div class="img-box thumbnail {{file.CoverCss}}">
                        <span class="icon edit" data-ng-click="edit(file)">
                            <a><i class="gallery-edit"></i></a>
                        </span>
                        <span class="icon trash" data-ng-click="delete(file)">
                            <i class="gallery-trash"></i>
                        </span>
                        <img data-ng-src="{{file.Url}}" class="img-responsive" alt="picture">
                        <strong class="clearfix label-cover" data-ng-show="file.IsCover">
                            <span>Cover</span>
                        </strong>
                    </div>
                </div>
                <!-- Spinner -->
                <div data-ng-repeat="file in draftFiles">
                    <div class="col-xs-6 col-md-4 img-container">
                        <div class="img-box">
                            <div class="spin-{{$index + 1}} img-spin-box"></div>
                        </div>
                    </div>
                </div>
                <!-- new image button -->
                <div class="col-xs-6 col-md-4 img-container" data-ng-hide="totalFiles >= 8 || files.length >= 8">
                    <label for="file-input">
                        <div class="img-box thumbnail new-img">
                            <i class="fa fa-plus fa-4x"></i>
                            <input id="file-input" name="image" type="file" multiple="" accept="image/*">
                        </div>
                    </label>

                    @*<div class="img-box thumbnail new-img">
                            <label for="file-input">
                                <div class="addnew">
                                    <i class="fa fa-plus fa-4x"></i>
                                </div>
                            </label>
                            <input id="file-input" name="image" type="file" multiple accept="image/*" />
                        </div>*@
                </div>
            </div>
        </div>
    </form>

    <!-- Modal - Delete Image -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Delete Image</h4>
                </div>
                <div class="modal-body">
                    <h4 class="modal-title">Are you sure you want to delete - {{file.Description}} ?</h4>
                </div>
                <div class="modal-footer">
                    <div class="pull-right">
                        <button type="button" class="btn-glow" data-dismiss="modal">Close</button>
                        <button type="button" class="btn-glow inverse" data-ng-click="deleteImage()">Delete</button>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="editModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Edit Image</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label for="input1" class="col-lg-2 control-label">Description:</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" placeholder="Max 30 characters" maxlength="30" data-ng-model="file.Description">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="checkbox">
                                <div class="col-md-10">
                                    <label>
                                        <input type="checkbox" data-ng-model="file.IsCover" />
                                        Make this image as Cover Image
                                    </label>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-glow" data-dismiss="modal">Close</button>
                    <button type="button" class="btn-glow success btn-finish" data-ng-click="editImage()">Save changes</button>
                </div>
            </div>
        </div>
    </div>


</div>
@section Scripts {
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/fileupload")
    <script>
        window.data = {
            id: 111
        };
    </script>
}